from __future__ import annotations

import json
from pathlib import Path

from refua_deploy.autodetect import ResolvedAutomation
from refua_deploy.models import DeploymentSpec


def render_cluster_bootstrap(
    spec: DeploymentSpec,
    resolved: ResolvedAutomation,
    output_dir: str | Path,
) -> list[Path]:
    out_root = Path(output_dir)
    bootstrap_dir = out_root / "bootstrap"
    bootstrap_dir.mkdir(parents=True, exist_ok=True)

    metadata_path = bootstrap_dir / "metadata.auto.json"
    metadata_payload = {
        "cloud": {
            "provider": spec.cloud.provider,
            "region": spec.cloud.region,
            "visibility": spec.cloud.visibility,
        },
        "runtime": {
            "namespace": spec.runtime.namespace,
            "orchestrator": spec.runtime.orchestrator,
        },
        "resolved": {
            "cluster_name": resolved.cluster_name,
            "node_instance_type": resolved.node_instance_type,
            "ingress_host": resolved.ingress_host,
            "allowed_hosts": resolved.allowed_hosts,
            "allowed_origins": resolved.allowed_origins,
        },
        "automation": {
            "provisioning_level": spec.automation.provisioning_level,
            "bootstrap_cluster": spec.automation.bootstrap_cluster,
            "auto_discover_network": spec.automation.auto_discover_network,
            "kubernetes_version": spec.automation.kubernetes_version,
            "node_count": spec.automation.node_count,
            "node_disk_gb": spec.automation.node_disk_gb,
        },
        "metadata": resolved.metadata,
    }
    metadata_path.write_text(
        json.dumps(metadata_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    script_path = bootstrap_dir / "cluster-bootstrap.sh"
    script_content = _cluster_bootstrap_script(spec=spec, resolved=resolved)
    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(0o755)

    network_env_path = bootstrap_dir / "network.auto.env"
    network_env_path.write_text(
        "\n".join(
            [
                f"REFUA_INGRESS_HOST={resolved.ingress_host or ''}",
                f"REFUA_ALLOWED_HOSTS={','.join(resolved.allowed_hosts)}",
                f"REFUA_ALLOWED_ORIGINS={','.join(resolved.allowed_origins)}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    return [metadata_path, script_path, network_env_path]


def _cluster_bootstrap_script(
    *, spec: DeploymentSpec, resolved: ResolvedAutomation
) -> str:
    provider = spec.cloud.provider
    region = spec.cloud.region or str(resolved.metadata.get("region") or "us-east-1")

    header = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Auto-generated by refua-deploy",
        f"# provider={provider}",
        f"# distribution={spec.kubernetes.distribution}",
        f"# cluster_name={resolved.cluster_name}",
        "",
        f"CLUSTER_NAME={resolved.cluster_name}",
        f"REGION={region}",
        f"NODE_COUNT={spec.automation.node_count}",
        f"NODE_INSTANCE_TYPE={resolved.node_instance_type}",
        f"NODE_DISK_GB={spec.automation.node_disk_gb}",
        f"K8S_VERSION={spec.automation.kubernetes_version}",
        "",
    ]

    commands = _provider_commands(spec=spec, resolved=resolved, region=region)
    return "\n".join([*header, *commands, ""]) + "\n"


def _provider_commands(
    *,
    spec: DeploymentSpec,
    resolved: ResolvedAutomation,
    region: str,
) -> list[str]:
    provider = spec.cloud.provider
    distribution = spec.kubernetes.distribution
    needs_gpu = spec.gpu.mode != "off" and (
        spec.gpu.mcp_enabled or spec.gpu.campaign_enabled
    )

    if provider == "aws" and distribution == "eks":
        subnet_ids = resolved.metadata.get("subnet_ids")
        subnet_flag = ""
        if isinstance(subnet_ids, list) and subnet_ids:
            subnet_flag = (
                f" --vpc-private-subnets {','.join(str(item) for item in subnet_ids)}"
            )
        gpu_label_flag = (
            " --node-labels nvidia.com/gpu.present=true" if needs_gpu else ""
        )
        return [
            "echo 'Creating EKS cluster with eksctl'",
            (
                "eksctl create cluster "
                '--name "$CLUSTER_NAME" '
                '--region "$REGION" '
                '--version "$K8S_VERSION" '
                '--nodes "$NODE_COUNT" '
                '--node-type "$NODE_INSTANCE_TYPE" '
                '--node-volume-size "$NODE_DISK_GB"'
                f"{subnet_flag}{gpu_label_flag}"
            ),
        ]

    if provider == "gcp" and distribution == "gke":
        zone = f"{region}-a"
        gpu_flag = " --accelerator type=nvidia-tesla-t4,count=1" if needs_gpu else ""
        return [
            "echo 'Creating GKE cluster with gcloud'",
            (
                'gcloud container clusters create "$CLUSTER_NAME" '
                '--region "$REGION" '
                '--cluster-version "$K8S_VERSION" '
                '--num-nodes "$NODE_COUNT" '
                '--machine-type "$NODE_INSTANCE_TYPE" '
                f'--node-locations "{zone}"{gpu_flag}'
            ),
        ]

    if provider == "azure" and distribution == "aks":
        resource_group = str(resolved.metadata.get("resource_group") or "refua-rg")
        gpu_flag = " --node-vm-size Standard_NC4as_T4_v3" if needs_gpu else ""
        return [
            "echo 'Creating AKS cluster with az cli'",
            (
                "az aks create "
                f'--resource-group "{resource_group}" '
                '--name "$CLUSTER_NAME" '
                '--location "$REGION" '
                '--kubernetes-version "$K8S_VERSION" '
                '--node-count "$NODE_COUNT" '
                '--node-vm-size "$NODE_INSTANCE_TYPE"'
                f"{gpu_flag}"
            ),
        ]

    if provider == "digitalocean" and distribution == "doks":
        return [
            "echo 'Creating DOKS cluster with doctl'",
            (
                'doctl kubernetes cluster create "$CLUSTER_NAME" '
                '--region "$REGION" '
                '--version "$K8S_VERSION" '
                '--size "$NODE_INSTANCE_TYPE" '
                '--count "$NODE_COUNT"'
            ),
        ]

    if distribution == "k3s":
        return [
            "echo 'Bootstrapping k3s control-plane node'",
            (
                "curl -sfL https://get.k3s.io | "
                "INSTALL_K3S_EXEC='server --write-kubeconfig-mode 644' sh -"
            ),
            "echo 'Join worker nodes with token from /var/lib/rancher/k3s/server/node-token'",
        ]

    if distribution == "rke2":
        return [
            "echo 'Bootstrapping RKE2 control-plane node'",
            "curl -sfL https://get.rke2.io | sh -",
            "sudo systemctl enable rke2-server.service",
            "sudo systemctl start rke2-server.service",
        ]

    if distribution == "kubeadm":
        return [
            "echo 'Bootstrapping kubeadm control-plane node'",
            'sudo kubeadm init --kubernetes-version "$K8S_VERSION"',
            "echo 'Install CNI and join workers with generated token.'",
        ]

    return [
        (
            "echo 'No turnkey bootstrap command for this provider/distribution; "
            "use metadata.auto.json and your platform IaC tooling.'"
        )
    ]
